Fix prettier issues

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,19 +2,19 @@ name: deploy
 
 on:
   workflow_dispatch:
-      inputs:
-        image_tag:
-          description: 'Docker image tag to deploy'
-          required: true
-          default: 'main'
-        environment:
-          description: 'Environment to deploy too'
-          required: true
-          default: 'sandbox'
-          type: choice
-          options:
-            - sandbox
-            - production
+    inputs:
+      image_tag:
+        description: "Docker image tag to deploy"
+        required: true
+        default: "main"
+      environment:
+        description: "Environment to deploy too"
+        required: true
+        default: "sandbox"
+        type: choice
+        options:
+          - sandbox
+          - production
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -27,21 +27,21 @@ jobs:
       - name: Get GHCR package hash
         id: get_package_hash
         run: |
-            container_id=$(gh api --paginate -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/MinBZK/packages/container/amt/versions | jq -r '.[] | select(.metadata.container.tags | contains(["${{ inputs.image_tag }}"])) | .name')
-            echo "container_id=$container_id" >> "$GITHUB_OUTPUT"
+          container_id=$(gh api --paginate -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/MinBZK/packages/container/amt/versions | jq -r '.[] | select(.metadata.container.tags | contains(["${{ inputs.image_tag }}"])) | .name')
+          echo "container_id=$container_id" >> "$GITHUB_OUTPUT"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: check correct name
         run: |
-            if [ -z "${{steps.get_package_hash.outputs.container_id}}" ]; then
-              echo "Variable is empty. Failing the workflow."
-              exit 1
-            fi
+          if [ -z "${{steps.get_package_hash.outputs.container_id}}" ]; then
+            echo "Variable is empty. Failing the workflow."
+            exit 1
+          fi
 
       - uses: actions/checkout@v4
         with:
-          repository: 'minbzk/ai-validation-infra'
+          repository: "minbzk/ai-validation-infra"
           ref: main
           token: ${{ secrets.GH_PAT }}
 
@@ -49,7 +49,6 @@ jobs:
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-
 
       - name: Make changes to the file
         run: |
